config/routes.rb
Rails.application.routes.draw do
  root "legislators#home"
  resources :legislators

  resources :graphs, only: [:index]

  post '/search' => 'legislators#search'
# get '/home' => 'legistlators#home'
end

#set up all controller's views,
# create the method that allows them to search for the legislator by last name
#set up form
#get info, pass back, iterate for columns

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :legislator
end

app/models/legislator.rb
class Legislator < ActiveRecord::Base
  has_many :contributions, dependent: :destroy

  candidate = OpenSecrets::Candidate.new(ENV['OPENSECRETS_TOKEN'])

  legis_sectors = candidate.industries({:cid => self.crp_id})["response"][kind.pluralize][kind]

  #collects and populates database with information regarding Legislator sector/industry and contribution info, depending on what attribute is passed through this method
  def collect_contribution_info(kind)

    #This designates how to call the API depending on what KIND is selected
    if kind == "sector"
      legis_sectors
    elsif kind == "industry"
      legis_sectors
    end


    #Each legislator is rendered a source, total, and pac info based on what KIND (sector, industry) is selected.
    sum = 0
    legis_sectors.each do |e|

      ### What an example hash looks like
        # x = legis_sectors[0] ->
        # {"industry_code"=>"H01",
        # "industry_name"=>"Health Professionals",
        # "indivs"=>"9100",
        # "pacs"=>"82500",
        # "total"=>"91600"}

       source = e[kind + "_name"]
       total = e["total"].to_i
       pac_total = e["pacs"].to_i
       indivs = e["indivs"].to_i

        #If Pac total is 0, then set pac_ratio to 0
      if pac_total == 0
        pac_ratio = 0
      else
        pac_ratio = ((total/pac_total)*100).round(1)
      end
       self.contributions.create!(source: source, total: total, pac_total:  pac_total,  pac_ratio: pac_ratio, indivs: indivs, kind: kind)
       #each time the loop is run the info is collected, each total contribution from either KIND (sector, industry) is totaled to create a composite summation of all sectors/industries
       sum += total
    end
    #Depending on what KIND is selected, update the DB with the corresponding information
    if kind == "sector"
      self.update(sector_sum: sum)
    elsif kind == "industry"
      self.update(industry_sum: sum)
    end
  end


###  !!!!!!FIX ME: NEED TO POPULATE DB WITH CONTRIBUTOR_TOTAL AND PAC_CONTRIBUTOR


  # def top_pacs
  #   top_pacs = OpenSecrets::Candidate.new.contributors(ENV['OPENSECRETS_TOKEN']).where(CID=self.crp_id)["response"]["contributor"]["contributors"]

  #   top_pacs.each do |x|
  # # for top_pacs[0] = {"org_name"=>"Occidental Petroleum", "total"=>"35000"}["total"]

  #       contributor_total = x["total"]
  #       pac_contributor = x["orgname"]
  #     end
  #  end


  def self.us_states
    [['Alabama', 'AL'],
    ['Alaska', 'AK'],
    ['Arizona', 'AZ'],
    ['Arkansas', 'AR'],
    ['California', 'CA'],
    ['Colorado', 'CO'],
    ['Connecticut', 'CT'],
    ['Delaware', 'DE'],
    ['District of Columbia', 'DC'],
    ['Florida', 'FL'],
    ['Georgia', 'GA'],
    ['Hawaii', 'HI'],
    ['Idaho', 'ID'],
    ['Illinois', 'IL'],
    ['Indiana', 'IN'],
    ['Iowa', 'IA'],
    ['Kansas', 'KS'],
    ['Kentucky', 'KY'],
    ['Louisiana', 'LA'],
    ['Maine', 'ME'],
    ['Maryland', 'MD'],
    ['Massachusetts', 'MA'],
    ['Michigan', 'MI'],
    ['Minnesota', 'MN'],
    ['Mississippi', 'MS'],
    ['Missouri', 'MO'],
    ['Montana', 'MT'],
    ['Nebraska', 'NE'],
    ['Nevada', 'NV'],
    ['New Hampshire', 'NH'],
    ['New Jersey', 'NJ'],
    ['New Mexico', 'NM'],
    ['New York', 'NY'],
    ['North Carolina', 'NC'],
    ['North Dakota', 'ND'],
    ['Ohio', 'OH'],
    ['Oklahoma', 'OK'],
    ['Oregon', 'OR'],
    ['Pennsylvania', 'PA'],
    ['Puerto Rico', 'PR'],
    ['Rhode Island', 'RI'],
    ['South Carolina', 'SC'],
    ['South Dakota', 'SD'],
    ['Tennessee', 'TN'],
    ['Texas', 'TX'],
    ['Utah', 'UT'],
    ['Vermont', 'VT'],
    ['Virginia', 'VA'],
    ['Washington', 'WA'],
    ['West Virginia', 'WV'],
    ['Wisconsin', 'WI'],
    ['Wyoming', 'WY']]
  end

   # def self.search_for(query)
  #   legislators = []

  #   if !query[:name].empty?
  #     # See if we have legis in our DB.
  #     legislators << Legislator.find_by_lastname(query[:name])

  #     if legislators.nil?
  #       # Didn't have legis with the last name in the DB
  #       # So, lets ask the API for legis with that last name
  #       legis_from_api = Sunlight::Legislator.all_where(:lastname => query[:name])

  #       # For legis that the API found with that last name
  #       legis_from_api.each do |l|
  #         # Create a legis in our DB.
  #         legislators << Legislator.create!(firstname: l.firstname, lastname: l.lastname, state: l.state)
  #       end
  #     end
  #   elsif !query[:state].empty?
  #     Sunlight::Legislator.all_where(:state => query[:state])
  #   else
  #     # we have a problem
  #   end

  #   legislators
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
end

app/controllers/legislators_controller.rb
class LegislatorsController < ApplicationController

  def home
  end

  def index
  end

  def show
    @legislator = Legislator.find(params[:id])
      # put bill shit here
    if !@legislator.contributions.present?
      @legislator.collect_contribution_info("sector")
      @legislator.collect_contribution_info("industry")
    end

  end

  def search
    # create a query hash from the form input
    query = {state: params[:state], name: params[:name]}

    @legislators = []
    if !query[:name].empty?
      legis_found = Legislator.where(lastname: query[:name])
      @legislators = legis_found unless legis_found.nil?


    elsif !query[:state].empty?
      legis_found = Legislator.where(state: query[:state])
      @legislators = legis_found unless legis_found.nil?
    end

    render :index
  end

private

  def legislator_params
    params.require(:legislator).permit(:id, :title, :firstname,:lastname, :party, :state, :state_name, :bioguide_id, :crp_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "OMGPoliticsBRO" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/legislators/home.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><div class= "logo"><i class="fi-dollar-bill size-36"></i> OMG <i class="fi-dollar-bill size-36"></i> </div></a></h1>
    </li>


    <div class = "section">
      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li class="has-dropdown">
            <a href="#"><i class="fi-list-thumbnails size-24"></i></a>
            <ul class="dropdown">
              <li><a href="#A1">About</a></li>
              <li><a href="#B1">Data Info</a></li>
              <li><a href="#C1">Contact</a></li>
            </ul>
          </li>
        </ul>

      </section>
    </div>
  </nav>



  <h1 class="text-center banner-text">OMGPoliticsBro</h1>
  <h2 class="text-center banner-text">Transparency. For da bros.</h2>


  <div id="banner">
    <div class= "sans">

      <div class="row">
        <div class="small-6 large-5 columns"></div>

        <div class = "home_search">
          <h2> Bro, like, Search for a Legislator</h2><br>

          <div class="row">
            <div class="medium-4 small-centered columns">
              <div class="row collapse">
               <div class="small-10 columns">
                <%= form_tag search_path do %>
                <%= select_tag(:state, options_for_select(Legislator.us_states)) %>

                <div><%=text_field_tag :name, nil, placeholder: 'Search by last name' %>

                  <div class= "button-wrap">

                    <%= button_tag(type: "submit", id: "Search", class: "search-button button postfix radius") do %>
                    <i class="fi-magnifying-glass"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

</div>
</div>




<div class="row">
  <div class="large-4 columns">
    <img src="http://www.brobible.com/wp-content/uploads/files/uploads/images/bro-life/'merica/soda-ban.jpg
    ">
  </div>
  <div class="large-8 columns">
    <div class= "sans">
      <h4><a name="A1">ABOUT</a></h4>
      <div class="row">
        <div class="large-6 columns">
          <p>So, Politics, you guys. Amiright? <br>So many issues, bro, so many stats. Here's an app help you keep on track with all that noise. OMGPoliticsBRO is a platform for identifying campaign finance patterns. Because patterns are fun, bro. All the cool kids are using them. </p>
        </div>
        <div class="large-6 columns">
          <p>The purpose of this app is to provide some insight into the national political economy as a way to help us bros keep it real. Because, money. So bros, look up those old farts who run the country so we can all OMG as one, united brodom. </p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="large-8 columns">
      <h4><a name="B1">Ah, numbers, I guess.</a></h4>
      <p>This app draws data from the Sunlight Congress and Influence Explorer API's, as well as from the OpenSecrets API. These APIs provide and track updated (through 2014) campaign finance data. </p>
      <p>Coupled together, the data provide us with insight into the context of camaign finance--how much money, where the money comes from, etc. As such, this app functions solely for transparency and accessibility, not commentary or conjecture.</p>
    </div>
    <div class="large-4 columns">
      <img src="http://production.cdn.annarbortees.com/public/spree/products/33681/large/thumb_white.png?1370828665">
    </div>
  </div>

  <footer class="row">
    <div class="large-12 columns">
      <div class="row">
        <div class="large-6 columns">
          <p><div><i class="fi-dollar-bill size-72"></i></div>To all the bros out there: DONT. STOP. BELEIVING. I GUESS.<p>
          </div>
          <div class="large-6 columns">
            <ul class="inline-list right">
              <li>Contact the Bromaster<%= mail_to "nnovak@fordham.edu" %></li>
              <li><a href="https://sunlightlabs.github.io/congress/">Sunlight</a></li>
              <li><a href="http://www.opensecrets.org/resources/create/api_doc.php">Open Secrets</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

  </body>

app/views/legislators/index.html.erb
<div class = "table-title">
  <div class="large-12 columns">
    <h1>Hey, um, I think you were looking for this!</h1>
  </div>
</div>

<div class = "table-legislator">
  <div class="text-centerlarge-12 columns">
    <table>
      <thead>
        <tr>
          <th width="75">Title</th>
          <th width="350">Name</th>
          <th width="150">Party</th>
          <th width="150">State</th>
          <th width="500">Office Address</th>

        </tr>
      </thead>
      <tbody>
       <% @legislators.each do |legislator|%>
       <tr class="legislator">
        <td class="title"><%= legislator.title %></td>
        <td class="name"><%= link_to legislator.firstname + " " + legislator.lastname, legislator_path(legislator)%></td>
        <td class="party"><%= legislator.party %></td>
        <td class="state"><%= legislator.state %></td>
        <td class="state"><%= legislator.congress_office %></td>
      </tr>
      <%end%>
    </tr>
  </tbody>
</table>
</div>
</div>


<footer class="row">
  <div class="large-12 columns">
    <p><%= link_to('Hey, um, jk, WE HAVE TO GO BACK, BRO', root_path) %></p>
  </div>
</footer>

app/views/legislators/show.html.erb
<div class="row">
<div class="large-3 columns">
<h1><div class= "logo"><i class="fi-dollar-bill size-36"></i> OMG <i class="fi-dollar-bill size-36"></i> </div></a></h1>
</div>
<div class="large-9 columns">
<ul class="inline-list right">

<li>Legend:</a></li>
<li><a href="#A1">Data Info</a></li>
</ul>
</div>
</div>

<div class="row">


<div class="large-9 push-3 columns">
<h3><%= @legislator.title + ". " + @legislator.firstname + " " + @legislator.lastname + " "%><small>--<%= @legislator.party %>-- <%= @legislator.state %></small></h3>
<p><%= link_to @legislator.website %></p>

<p> <%= @legislator.congress_office %></p>

<p>

  Campaign Finance by Sectors and Industries:
  <div class = "loop-sector-container">
    <% @legislator.contributions.each do |c| %>

      <!-- Composes CSS barchart from the "total" data, scaled to the amount of money calculated. Note that the decision to scale this further by a factor of "1000" reflects the diffuse spectrum of total monetary contribution, meaning that this factor serves as a mid-range value to scale back the css values of the bigger contributions and to allow the smaller values to retain apparent scaled visualization-->
      <div class ="contri">
        <div class = "contributions_chart">
          <div style="width:<%= c.total/1000 %>px" class="contribution">

              <%= c.source%>
              <%= number_to_currency(c.total) %>
          </div>
        </div>
      </div>
    <%end%>
  </div>


</p>

<h3><a name="A1">Data Info</a></h3><br>

<p> The above data, pulled from the <a href="http://www.opensecrets.org/resources/create/api_doc.php">OpenSecrets API</a> provides up-to-date Campaign Finance information reagarding Industy and Sector contributions. For reference, however, please note the descriptions of the following classifications, taken from the OpenSecrets website. Please note that full, detailed descriptions of these data categories can be found <a href="http://www.opensecrets.org/industries/slist.php">here.</a></p>


<h4><a href="http://www.opensecrets.org/industries/indus.php?ind=N">"Other"</a> </h4>
<p>
This sector is home to a variety of industries that don't fall under any business, labor or ideological groupings. The biggest dollars, by far, come from the large and diverse group of donors listing their occupation as "retired."

Other categories include educators, government employees (though not their unions), nonprofit organizations, religious groups and members of the armed forces. This sector contributed more than $400 million to federal parties and candidates during the 2008 election cycle.
</p>

<h4><a href="http://www.opensecrets.org/industries/indus.php?ind=N">"Misc Business"</a> </h4>
<p>
The broad miscellaneous business sector encompasses a range of industries, from the manufacturing, textiles, steel and chemical industries to consumer retail goods, restaurants, beer wholesalers and funeral services. This sector also includes gambling, tourism, food and beverages.
</p>
</div>


<div class="large-3 pull-9 columns">

<p><%= image_tag "https://raw.githubusercontent.com/unitedstates/images/gh-pages/congress/450x550/#{@legislator.bioguide_id}.jpg" %></p>

<ul class="side-nav">
<li>Sector Sum:  <%= number_to_currency(@legislator.sector_sum)%></a></li>
<li>Industry Sum:  <%= number_to_currency(@legislator.industry_sum)%></a></li>


<li><a href="https://petitions.whitehouse.gov/petitions">Petition <%= @legislator.title + ". " + @legislator.firstname + " " + @legislator.lastname + " "%></a></li>


</ul>
</div>
</div>



<footer class="row">
<div class="large-12 columns">
<hr/>
<div class="row">
<div class="large-6 columns">
<p>Hey! What are you doing down here?!! Get back up there!! Go on, giit!!.</p>
</div>
<div class="large-6 columns">
<ul class="inline-list right">
<li><%= link_to('Home', root_path) %></li>
<li>Contact the Bromaster<%= mail_to "nnovak@fordham.edu" %></li>

</ul>
</div>
</div>
</div>
</footer>